---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zdh.
--- DateTime: 2019/1/16 19:30
---

EventIds = {
    ItemClicked = '2001';
    GetScore = '2002';
    GameOver = '2003';
    BackStart = '2004';
    ShowScore = '2005';
}