---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zdh.
--- DateTime: 2018/11/11 21:01
---

require("Logic/LLuaComponent")

GameLogic = {
    componentName="",
    ---@type UnityEngine.GameObject
    gameObject = nil,
    ItemBgs,
}

GameLogic.__index = GameLogic

setmetatable(GameLogic,LLuaComponent)

---@param gameObject UnityEngine.GameObject
function GameLogic:New(componentName,gameObject)
    local result = {}
    result = LLuaComponent:New(componentName,gameObject)
    setmetatable(result,GameLogic)
    result.componentName = componentName
    result.gameObject = gameObject
    result.self = result
    return result
end

function GameLogic:Awake()
    log("触发继承的Awake")
    log(self.componentName)
    log(self.gameObject.name)
    self.ItemBgs = self.gameObject.transform:Find('ItemBgs');
    resMgr:LoadPrefab("gameprefabs",{'BgItem'},function (objs)
        self:InitBgItems(objs)
    end)
end

function GameLogic:InitBgItems(objs)
    log(objs[0].name)
    for x = -4, 4, 1 do
        for y = 4, -4, -1 do
            ---@type UnityEngine.GameObject
            local item = newObject(objs[0])
            item.transform.parent = self.ItemBgs
            item.name = x .. y ..''
            item.transform.position = Vector3(x,y,0)
        end
    end
    log(self.componentName)
end

return GameLogic