---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zdh.
--- DateTime: 2018/11/8 22:39
---



---@class LLuaComponent lua脚本的基类
LLuaComponent={
    componentName="",
    ---@type UnityEngine.GameObject
    gameObject=nil
}

LLuaComponent.__index = LLuaComponent

---@param gameObject UnityEngine.GameObject
function LLuaComponent:New(componentName,gameObject)
    local result = {}
    setmetatable(result,LLuaComponent)
    result.componentName = componentName
    result.gameObject = gameObject;
    return result
end

function LLuaComponent:Awake()
    log('执行lua端的Awake')
end

function LLuaComponent:Start()
    log('执行lua端的Start')
end

function LLuaComponent:OnEnable()
    log('执行lua端的OnEnable')
end

function LLuaComponent:OnBecameInvisible()
    log('执行lua端的OnBecameInvisible')
end

function LLuaComponent:OnBecameVisible()
    log('执行lua端的OnBecameVisible')
end

function LLuaComponent:OnCollisionEnter(collision)
    log('执行lua端的OnCollisionEnter')
end

function LLuaComponent:OnCollisionStay(collision)
    log('执行lua端的OnCollisionStay')
end

function LLuaComponent:OnCollisionExit(collision)
    log('执行lua端的OnCollisionExit')
end

function LLuaComponent:OnCollisionEnter2D(collision)
    log('执行lua端的OnCollisionEnter2D')
end

function LLuaComponent:OnCollisionStay2D(collision)
    log('执行lua端的OnCollisionStay2D')
end

function LLuaComponent:OnCollisionExit2D(collision)
    log('执行lua端的OnCollisionExit2D')
end

function LLuaComponent:OnTriggerEnter(collision)
    log('执行lua端的OnTriggerEnter')
end

function LLuaComponent:OnTriggerStay(collision)
    log('执行lua端的OnTriggerStay')
end

function LLuaComponent:OnTriggerExit(collision)
    log('执行lua端的OnTriggerExit')
end

function LLuaComponent:OnTriggerEnter2D(collision)
    log('执行lua端的OnTriggerEnter')
end

function LLuaComponent:OnTriggerStay2D(collision)
    log('执行lua端的OnTriggerStay')
end

function LLuaComponent:OnTriggerExit2D(collision)
    log('执行lua端的OnTriggerExit')
end

function LLuaComponent:OnLevelWasLoaded(level)
    log('执行lua端的OnLevelWasLoaded')
end

function LLuaComponent:OnApplicationFocus(focus)
    log('执行lua端的OnApplicationFocus'.. tostring(focus))
end

function LLuaComponent:OnApplicationQuit()
    log('执行lua端的OnApplicationQuit')
end

function LLuaComponent:OnDestroy()
    log('执行lua端的OnDestroy')
end

function LLuaComponent:OnDisable()
    log('执行lua端的OnDisable')
end

return LLuaComponent