---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zdh.
--- DateTime: 2019/1/12 21:06
---

require("Logic/LLuaComponent")
require("Common/eventids")
require("EventDispatcher")

Event = require("events")

---@class
GameItem = {
    x,
    y,
    colorIndex,
    moveSpeed = 0.25,

}

GameItem.__index = GameItem

---@param componentName string
---@param gameObject UnityEngine.GameObject
function GameItem:New(componentName, gameObject)
    local result = LLuaComponent:New(componentName, gameObject)
    setmetatable(result, GameItem)
    result.moveSpeed = 0.25
    return result
end

function GameItem:Awake()
    self.eventListener = EventTriggerListener.GetListener(self.gameObject)
    self.eventListener:SetLuaTable(self)
    self.eventListener.onPointerClick = self.eventListener.onPointerClick + self.onPointerClick
end

function GameItem:onPointerClick(go, eventData)
    log('点击了' .. self.x .. self.y .. '位置上的Item')
    EventDispatcher:Dispatcher(EventIds.ItemClicked, self)
end

function GameItem:MoveTo(toX, toY, callback)
    local ox = self.x - toX
    local oy = self.y - toY
    local dur = self.moveSpeed * 1
    if math.abs(ox) > 0 then
        dur = self.moveSpeed * math.abs(ox)
    else
        dur = self.moveSpeed * math.abs(oy)
    end
    ---@type UnityEngine.Transform
    self.transform = self.gameObject.transform
    ---@type
    local tweener = self.transform:DOMove(Vector3(toX, toY, 0), dur)
    tweener.onComplete = callback
end

return GameItem