---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zdh.
--- DateTime: 2018/10/29 23:30
---

require("Logic/GameLogic")
require("EventDispatcher")
require('Common/eventids')

GameCtrl = {};
local this = GameCtrl;

local panel;
---@type UnityEngine.Transform
local transform;
---@type UnityEngine.GameObject
local gameObject;

local lastScore = 0

--构建函数--
function GameCtrl.New()
    logWarn("gameCtrl.New--->>");
    return this;
end

function GameCtrl.Awake()
    logWarn("gameCtrl.Awake--->>");
    panelMgr:CreatePanel('Game', this.OnCreate);
    EventDispatcher:AddEventListener(EventIds.GetScore, function(score)
        this.GetScore(score)
    end)
    EventDispatcher:AddEventListener(EventIds.GameOver, function()
        this.GameOver()
    end)
end

--启动事件--
function GameCtrl.OnCreate(obj)
    gameObject = obj;
    transform = gameObject.transform;
    panel = gameObject:GetComponent('LuaBehaviour');
    this.lastTime = 5
    this.backBtnListener = EventTriggerListener.GetListener(GamePanel.backBtn.gameObject);
    this.backBtnListener.onPointerClick = this.backBtnListener.onPointerClick + GameCtrl.OnBackBtnClick
    coroutine.start(this.LastTimeShow);
end

--关闭事件--
function GameCtrl.Close()
    log('开始关闭游戏界面界面')
    panelMgr:ClosePanel('Start');
end

---@param go UnityEngine.GameObject
function GameCtrl.OnBackBtnClick(go, eventData)
    log('点击返回按钮')
    local ctrl = CtrlManager.GetCtrl(CtrlNames.Start);
    if ctrl ~= nil then
        ctrl:Awake();
    end
    coroutine.stop(this.LastTimeShow)
    EventDispatcher:Dispatcher(EventIds.BackStart)
    EventDispatcher:RemoveEventListeners(EventIds.GetScore)
    EventDispatcher:RemoveEventListeners(EventIds.GameOver)
    panelMgr:ClosePanel('Game')
end

function GameCtrl.GetScore(score)
    lastScore = lastScore + score
    GamePanel.scoreText.text = lastScore .. ''
end

function GameCtrl.GameOver()
    coroutine.stop(this.LastTimeShow)
    local ctrl = CtrlManager.GetCtrl(CtrlNames.GameOver);
    if ctrl ~= nil then
        ctrl:Awake();
    end
    EventDispatcher:Dispatcher(EventIds.ShowScore, lastScore)
end

--显示倒计时
function GameCtrl:LastTimeShow()
    while true do
        GamePanel.lastTimeText.text = this.lastTime .. 's'
        coroutine.wait(1.0)
        this.lastTime = this.lastTime - 1
        if this.lastTime <= 0 then
            GamePanel.lastTimeText.text = this.lastTime .. 's'
            this.GameOver()
            break
        end
    end
end
