---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zdh.
--- DateTime: 2018/10/29 23:30
---

---@type UnityEngine.Transform
local transform;
---@type UnityEngine.GameObject
local gameObject;

GamePanel = {};
local this = GamePanel;

--启动事件--
function GamePanel.Awake(obj)
    gameObject = obj;
    transform = obj.transform;
    this.InitPanel();
    this.lastTimeText = transform:Find('LastTimeBg/Text')
    ---@type Unity
    this.scoreText = transform:Find('ScoreBg/ScoreText/ScoreValueText'):GetComponent('Text')
    this.backBtn = transform:Find('BackBtn')

    logWarn("Awake lua--->>"..gameObject.name);
end

--初始化面板--
function GamePanel.InitPanel()

end

--单击事件--
function GamePanel.OnDestroy()
    logWarn("OnDestroy---->>>");
end

