---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zdh.
--- DateTime: 2018/10/29 23:30
---

---@type UnityEngine.Transform
local transform;
---@type UnityEngine.GameObject
local gameObject;

GameOverPanel = {};
local this = GameOverPanel;

--启动事件--
function GameOverPanel.Awake(obj)
    gameObject = obj;
    transform = obj.transform;
    this.InitPanel();
    this.scoreText = transform:Find('Bg/Score'):GetComponent('Text')
    this.backBtn = transform:Find('Bg/BackBtn')

    logWarn("Awake lua--->>" .. gameObject.name);
end

--初始化面板--
function GameOverPanel.InitPanel()

end

--单击事件--
function GameOverPanel.OnDestroy()
    logWarn("OnDestroy---->>>");
end

