---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zdh.
--- DateTime: 2018/10/29 23:30
---

local transform;
local gameObject;

StartPanel = {};
local this = StartPanel;

--启动事件--
function StartPanel.Awake(obj)
    gameObject = obj;
    transform = obj.transform;
    this.InitPanel();
    logWarn("Awake lua--->>"..gameObject.name);
end

--初始化面板--
function StartPanel.InitPanel()
    this.exitGameBtn = transform:Find('ExitGameBtn').gameObject;
    this.startBtn = transform:Find("PlayBtn").gameObject;
end

--单击事件--
function StartPanel.OnDestroy()
    logWarn("OnDestroy---->>>");
end

